### ISSUE TITLE
MIT OCW courses not available anywhere on YouTube

### ISSUE THREAD

**Issue by th3sn3k** [llSourcell/Learn_Machine_Learning_in_3_Months#13] opened 2018-06-17 06:34 UTC
This Issue started a day back It seems all videos from MIT OCW have been blocked on every country I checked with YouTube restriction checker.

Hope you can suggest an alternative to the OCW courses.

**Comment by AnupamKhurana** [comment] 2018-06-18 05:58
Yes, I am facing the same issue. "MIT OpenCourseWare" on youtube isn't available for now in India at least.

**Comment by lamhoangtung** [comment] 2018-06-18 06:00
Have you tried the OpenCourseWare website instead ? It’s working fine for
me (i’m in vietnam btw)
Vào Th 2, 18 thg 6, 2018 lúc 12:59 AnupamKhurana <notifications@github.com>
đã viết:

**Comment by AnupamKhurana** [comment] 2018-06-18 06:03
Same problem on the OpenCourseWare website...

**Comment by yaakash** [comment] 2018-06-21 11:31
Website of OCW uses a different player, in case of Linear algebra course, its running.

**Comment by cksajil** [comment] 2018-06-21 11:49
I think the problem is fixed now. All videos are available in YouTube as before.

**Comment by AnupamKhurana** [comment] 2018-06-21 16:13
issue is resolved

**Closed as completed** 2018-06-22 09:48 UTC

**Comment by happytalkman** [comment] 2018-09-22 20:41
goooood
